const NotificationTemplate = require('../../models/NotificationTemplate');

const SUPPORTED_VARIABLES = [
  'student_name',
  'register_number',
  'parent_name',
  'subject',
  'hour',
  'date',
  'teacher_name',
  'class',
  'section',
  'department',
  'total',
  'present',
  'absent',
  'od',
  'hostel',
  'report_link',
];

const DEFAULT_TEMPLATES = [
  {
    templateKey: 'PARENT_ABSENCE_WHATSAPP',
    name: 'Parent Absence Alert (WhatsApp)',
    eventType: 'ABSENCE_ALERT',
    channel: 'WHATSAPP',
    recipientRole: 'PARENT',
    title: 'KEC Attendance Alert',
    body: '*KONGU ENGINEERING COLLEGE (AUTONOMOUS)*\n\nDear Parent,\nYour ward *{{student_name}}* ({{register_number}}) of *{{class}}* was marked *ABSENT* today.\n\n📚 *Subject:* {{subject}}\n⏰ *Period:* Hour {{hour}}\n📅 *Date:* {{date}}\n\n_This is an automated attendance alert from KEC SmartAttend._',
    supportedVariables: ['student_name', 'register_number', 'class', 'subject', 'hour', 'date'],
  },
  {
    templateKey: 'PARENT_ABSENCE_IN_APP',
    name: 'Parent Absence Alert (In-App)',
    eventType: 'ABSENCE_ALERT',
    channel: 'IN_APP',
    recipientRole: 'PARENT',
    title: 'Attendance Alert: Absence Notification',
    body: 'Your ward {{student_name}} ({{register_number}}) was marked ABSENT for {{subject}} (Hour {{hour}}) on {{date}}.',
    supportedVariables: ['student_name', 'register_number', 'subject', 'hour', 'date'],
  },
  {
    templateKey: 'STUDENT_ABSENCE_IN_APP',
    name: 'Student Absence Notice (In-App)',
    eventType: 'ABSENCE_ALERT',
    channel: 'IN_APP',
    recipientRole: 'STUDENT',
    title: 'Attendance Alert: Marked Absent',
    body: 'You were marked ABSENT for {{subject}} (Hour {{hour}}) on {{date}}.',
    supportedVariables: ['subject', 'hour', 'date'],
  },
  {
    templateKey: 'HOD_SUMMARY_WHATSAPP',
    name: 'HOD Attendance Summary (WhatsApp)',
    eventType: 'HOD_ATTENDANCE_SUMMARY',
    channel: 'WHATSAPP',
    recipientRole: 'HOD',
    title: 'HOD Hourly Attendance Summary',
    body: '*KEC DEPARTMENT ATTENDANCE SUMMARY*\n\n📊 *Class:* {{class}}\n📖 *Subject:* {{subject}}\n👨‍🏫 *Faculty:* {{teacher_name}}\n⏰ *Hour:* {{hour}}\n\n👥 *Present:* {{present}} / {{total}}\n❌ *Absent:* {{absent}}\n\n_Generated by KEC SmartAttend Engine._',
    supportedVariables: ['class', 'subject', 'teacher_name', 'hour', 'present', 'total', 'absent'],
  },
  {
    templateKey: 'HOD_SUMMARY_IN_APP',
    name: 'HOD Attendance Summary (In-App)',
    eventType: 'HOD_ATTENDANCE_SUMMARY',
    channel: 'IN_APP',
    recipientRole: 'HOD',
    title: 'Hourly Attendance Summary',
    body: 'Hour {{hour}} attendance finalized for {{class}} - {{subject}}: {{present}}/{{total}} present, {{absent}} absent.',
    supportedVariables: ['class', 'subject', 'hour', 'present', 'total', 'absent'],
  },
  {
    templateKey: 'WARDEN_ABSENCE_IN_APP',
    name: 'Warden Hostel Absence Alert (In-App)',
    eventType: 'ABSENCE_ALERT',
    channel: 'IN_APP',
    recipientRole: 'WARDEN',
    title: 'Hostel Student Absent Alert',
    body: 'Hostel resident {{student_name}} ({{register_number}}) was marked ABSENT for {{subject}} (Hour {{hour}}) on {{date}}.',
    supportedVariables: ['student_name', 'register_number', 'subject', 'hour', 'date', 'hostel'],
  },
  {
    templateKey: 'LOW_ATTENDANCE_WHATSAPP',
    name: 'Low Attendance Warning (WhatsApp)',
    eventType: 'LOW_ATTENDANCE_ALERT',
    channel: 'WHATSAPP',
    recipientRole: 'PARENT',
    title: 'Low Attendance Notice',
    body: '*ATTENDANCE WARNING — KEC*\n\nDear Parent of *{{student_name}}* ({{register_number}}),\nOverall attendance is currently *{{present}}%* (Minimum 75% required for examination eligibility).\n\nPlease meet the Head of Department.',
    supportedVariables: ['student_name', 'register_number', 'present'],
  },
  {
    templateKey: 'OD_NOTIFICATION_IN_APP',
    name: 'OD Request Status (In-App)',
    eventType: 'OD_NOTIFICATION',
    channel: 'IN_APP',
    recipientRole: 'STUDENT',
    title: 'On-Duty Request Update',
    body: 'Your OD request for {{subject}} has been processed.',
    supportedVariables: ['subject', 'date'],
  },
];

class TemplateService {
  constructor() {
    this.supportedVariables = SUPPORTED_VARIABLES;
  }

  /**
   * Seed default templates if they do not already exist in the database.
   */
  async seedDefaultTemplates() {
    try {
      for (const tmpl of DEFAULT_TEMPLATES) {
        const exists = await NotificationTemplate.findOne({ templateKey: tmpl.templateKey });
        if (!exists) {
          await NotificationTemplate.create(tmpl);
        }
      }
    } catch (err) {
      console.warn('[TemplateService] Seed warning:', err.message);
    }
  }

  /**
   * Validate that all placeholders in a template string belong to supported variables.
   * @param {string} text - Template title or body
   * @returns {{ isValid: boolean, invalidVariables: string[] }}
   */
  validateVariables(text) {
    if (!text) return { isValid: true, invalidVariables: [] };

    const regex = /\{\{([a-zA-Z0-9_]+)\}\}/g;
    const invalidVariables = [];
    let match;

    while ((match = regex.exec(text)) !== null) {
      const varName = match[1];
      if (!this.supportedVariables.includes(varName)) {
        invalidVariables.push(varName);
      }
    }

    return {
      isValid: invalidVariables.length === 0,
      invalidVariables,
    };
  }

  /**
   * Replace placeholders with payload data.
   */
  renderString(templateString, payload = {}) {
    if (!templateString) return '';

    return templateString.replace(/\{\{([a-zA-Z0-9_]+)\}\}/g, (match, key) => {
      // Map common alternative key names
      const valMap = {
        student_name: payload.studentName || payload.student_name,
        register_number: payload.registerNumber || payload.register_number,
        parent_name: payload.parentName || payload.parent_name,
        subject: payload.subjectName || payload.subject,
        hour: payload.hour,
        date: payload.date ? (typeof payload.date === 'string' ? payload.date.slice(0, 10) : new Date(payload.date).toLocaleDateString('en-IN')) : new Date().toLocaleDateString('en-IN'),
        teacher_name: payload.teacherName || payload.teacher_name,
        class: payload.className || payload.class,
        section: payload.section || 'D',
        department: payload.departmentName || payload.department || 'ECE',
        total: payload.totalStudents ?? payload.total,
        present: payload.presentCount ?? payload.present,
        absent: payload.absentCount ?? payload.absent,
        od: payload.odCount ?? payload.od ?? 0,
        hostel: payload.hostelName || payload.hostel || 'KEC Hostel',
        report_link: payload.reportLink || payload.report_link || '#',
      };

      const val = valMap[key];
      return val !== undefined && val !== null ? String(val) : match;
    });
  }

  /**
   * Format payload into channel-specific title and body.
   */
  format(type, channel, payload = {}, role = 'PARENT') {
    // 1. Try resolving template
    const defaultTemplate = DEFAULT_TEMPLATES.find(
      (t) => t.eventType === type && t.channel === channel && (t.recipientRole === role || t.recipientRole === 'PARENT')
    ) || DEFAULT_TEMPLATES.find((t) => t.eventType === type && t.channel === channel) || {
      title: payload.title || 'Attendance Alert',
      body: payload.message || payload.body || 'New attendance update from KEC SmartAttend.',
    };

    const renderedTitle = this.renderString(defaultTemplate.title, payload);
    const renderedBody = this.renderString(defaultTemplate.body, payload);

    return {
      title: renderedTitle,
      body: renderedBody,
      message: renderedBody,
      subject: renderedTitle,
      data: payload,
    };
  }

  /**
   * Generate real-time preview of a template with sample data.
   */
  preview(templateBody, templateTitle, customPayload = null) {
    const samplePayload = customPayload || {
      studentName: 'SARAN K N',
      registerNumber: '24ECR177',
      parentName: 'NATARAJAN N',
      subjectName: 'Digital Signal Processing',
      hour: 1,
      date: new Date().toLocaleDateString('en-IN'),
      teacherName: 'Ms. N. Indhumathi',
      className: 'ECE III Year - Section D',
      section: 'D',
      departmentName: 'Electronics and Communication Engineering',
      totalStudents: 61,
      presentCount: 58,
      absentCount: 3,
      odCount: 1,
      hostelName: 'KEC Men\'s Hostel - Block A',
      reportLink: 'https://smartattend.kongu.edu/reports/session/123',
    };

    const validationTitle = this.validateVariables(templateTitle);
    const validationBody = this.validateVariables(templateBody);

    return {
      isValid: validationTitle.isValid && validationBody.isValid,
      invalidVariables: [...new Set([...validationTitle.invalidVariables, ...validationBody.invalidVariables])],
      renderedTitle: this.renderString(templateTitle, samplePayload),
      renderedBody: this.renderString(templateBody, samplePayload),
      samplePayload,
    };
  }
}

module.exports = new TemplateService();
